###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deraining_2070images'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 3
  NUM_EPOCHS: 1000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 400
  VAL_PS: 400
  # TRAIN_DIR: '/content/drive/MyDrive/DERAIN/train'       # path to training data
  # VAL_DIR: '/content/drive/MyDrive/DERAIN/test' # path to validation data
  TRAIN_DIR: '/content/drive/MyDrive/DERAIN/DATA_20220325/train'       # path to training data
  VAL_DIR: '/content/drive/MyDrive/DERAIN/DATA_20220325/validate' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
